import type { RentalCar } from "../../types/rentalCar";

export const homePageData = [
  {
    title: "The Best Platform for Car Rental",
    description:
      "Ease of doing a car rental safely and reliably. Of course at a low price.",
    image: "/car.png",
    buttonText: "Rental Car",
    buttonLink: "/",
  },
  {
    title: "Easy way to rent a car at a low price",
    description:
      "Providing cheap car rental services and safe and comfortable facilities.",
    image: "/car.png",
    buttonText: "Rental Car",
    buttonLink: "/",
  },
];

export const popularCarsData: RentalCar[] = [
  {
    id: "1",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    dailyPriceWithDiscount: 90,
    image: "/car1.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "2",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    image: "/car2.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "3",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    dailyPriceWithDiscount: 90,
    image: "/car3.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "4",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    dailyPriceWithDiscount: 90,
    image: "/car4.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "5",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,

    image: "/car5.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
];

export const recommendedCarsData: RentalCar[] = [
  {
    id: "101",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    dailyPriceWithDiscount: 90,
    image: "/car1.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "102",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    image: "/car2.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "103",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    dailyPriceWithDiscount: 90,
    image: "/car3.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "104",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    dailyPriceWithDiscount: 90,
    image: "/car4.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "105",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,

    image: "/car5.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "106",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    dailyPriceWithDiscount: 90,
    image: "/car1.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "107",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    image: "/car2.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "108",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    dailyPriceWithDiscount: 90,
    image: "/car3.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "109",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    dailyPriceWithDiscount: 90,
    image: "/car4.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
  {
    id: "110",
    vehicleBrand: "Toyota",
    vehicleBodyType: "Sedan",
    dailyPrice: 100,
    image: "/car5.png",
    fuelCapacity: 90,
    transmission: "Manual",
    passengerCapacity: 4,
  },
];
